### ISSUE TITLE
TODO list for basic functionalities

### ISSUE THREAD

**Issue by Bubobubobubobubo** [Bubobubobubobubo/BuboQuark#1]
I would like to keep things minimal but expect to have the following features:

**Deployment/Installation**:

- [x] no hardcoded paths / environment specific variables
- [x] #2
- [ ] basic small sound library to play with (taken from my base sample folder)
- [x] better user feedback in the debug console (install state, paths, etc.)

**Sampling**:

- [ ] Looping buffers: looping over samples with a rate in beats
- [x] Granular buffers: basic granulation of sound files
- [ ] Reverse playback: playing sounds in reverse easily
- [x] Pitched playback: similar to SuperDirt sample pitching model
- [ ] Wavetable playback: download a library of wavetables and simple pitched playback

**Audio**:

- [x] amplitude should be consistent over different synths / samplers
- [x] easy audio-in / audio-out routing (doable already)

**Scrutability**:

- [x] Print the list of currently available audio samples
- [x] Print the list and parameters of available synths
  - [x] print it for one synth only
- [x] Feedback on server state (every beat or so)

I'll keep this list updated but having the basics ready would be awesome.
